#ifndef GPIO_h
#define GPIO_h

#include "memory.h"

#define MODER(periph)   ((volatile unsigned int *)(periph + 0x00))
#define OTYPER(periph)  ((volatile unsigned int *)(periph + 0x04))
#define OSPEEDR(periph) ((volatile unsigned int *)(periph + 0x08))
#define PUPDR(periph)   ((volatile unsigned int *)(periph + 0x0c))
#define IDR(periph)     ((volatile unsigned int *)(periph + 0x10))
#define ODR(periph)     ((volatile unsigned int *)(periph + 0x14))
#define BSRR(periph)    ((volatile unsigned int *)(periph + 0x18))
#define LCKR(periph)    ((volatile unsigned int *)(periph + 0x1c))
#define AFRL(periph)    ((volatile unsigned int *)(periph + 0x20))
#define AFRH(periph)    ((volatile unsigned int *)(periph + 0x24))

#define GPIOA_MODER      (volatile unsigned int *)(GPIOA + 0x00)
#define GPIOA_OTYPER     (volatile unsigned int *)(GPIOA + 0x04)
#define GPIOA_OSPEEDR    (volatile unsigned int *)(GPIOA + 0x08)
#define GPIOA_PUPDR      (volatile unsigned int *)(GPIOA + 0x0c)
#define GPIOA_IDR        (volatile unsigned int *)(GPIOA + 0x10)
#define GPIOA_ODR        (volatile unsigned int *)(GPIOA + 0x14)
#define GPIOA_BSRR       (volatile unsigned int *)(GPIOA + 0x18)
#define GPIOA_LCKR       (volatile unsigned int *)(GPIOA + 0x1c)
#define GPIOA_AFRL       (volatile unsigned int *)(GPIOA + 0x20)
#define GPIOA_AFRH       (volatile unsigned int *)(GPIOA + 0x24)

#define GPIOB_MODER      (volatile unsigned int *)(GPIOB + 0x00)
#define GPIOB_OTYPER     (volatile unsigned int *)(GPIOB + 0x04)
#define GPIOB_OSPEEDR    (volatile unsigned int *)(GPIOB + 0x08)
#define GPIOB_PUPDR      (volatile unsigned int *)(GPIOB + 0x0c)
#define GPIOB_IDR        (volatile unsigned int *)(GPIOB + 0x10)
#define GPIOB_ODR        (volatile unsigned int *)(GPIOB + 0x14)
#define GPIOB_BSRR       (volatile unsigned int *)(GPIOB + 0x18)
#define GPIOB_LCKR       (volatile unsigned int *)(GPIOB + 0x1c)
#define GPIOB_AFRL       (volatile unsigned int *)(GPIOB + 0x20)
#define GPIOB_AFRH       (volatile unsigned int *)(GPIOB + 0x24)

#define GPIOC_MODER      (volatile unsigned int *)(GPIOC + 0x00)
#define GPIOC_OTYPER     (volatile unsigned int *)(GPIOC + 0x04)
#define GPIOC_OSPEEDR    (volatile unsigned int *)(GPIOC + 0x08)
#define GPIOC_PUPDR      (volatile unsigned int *)(GPIOC + 0x0c)
#define GPIOC_IDR        (volatile unsigned int *)(GPIOC + 0x10)
#define GPIOC_ODR        (volatile unsigned int *)(GPIOC + 0x14)
#define GPIOC_BSRR       (volatile unsigned int *)(GPIOC + 0x18)
#define GPIOC_LCKR       (volatile unsigned int *)(GPIOC + 0x1c)
#define GPIOC_AFRL       (volatile unsigned int *)(GPIOC + 0x20)
#define GPIOC_AFRH       (volatile unsigned int *)(GPIOC + 0x24)

#define GPIOD_MODER      (volatile unsigned int *)(GPIOD + 0x00)
#define GPIOD_OTYPER     (volatile unsigned int *)(GPIOD + 0x04)
#define GPIOD_OSPEEDR    (volatile unsigned int *)(GPIOD + 0x08)
#define GPIOD_PUPDR      (volatile unsigned int *)(GPIOD + 0x0c)
#define GPIOD_IDR        (volatile unsigned int *)(GPIOD + 0x10)
#define GPIOD_ODR        (volatile unsigned int *)(GPIOD + 0x14)
#define GPIOD_BSRR       (volatile unsigned int *)(GPIOD + 0x18)
#define GPIOD_LCKR       (volatile unsigned int *)(GPIOD + 0x1c)
#define GPIOD_AFRL       (volatile unsigned int *)(GPIOD + 0x20)
#define GPIOD_AFRH       (volatile unsigned int *)(GPIOD + 0x24)

#define GPIOE_MODER      (volatile unsigned int *)(GPIOE + 0x00)
#define GPIOE_OTYPER     (volatile unsigned int *)(GPIOE + 0x04)
#define GPIOE_OSPEEDR    (volatile unsigned int *)(GPIOE + 0x08)
#define GPIOE_PUPDR      (volatile unsigned int *)(GPIOE + 0x0c)
#define GPIOE_IDR        (volatile unsigned int *)(GPIOE + 0x10)
#define GPIOE_ODR        (volatile unsigned int *)(GPIOE + 0x14)
#define GPIOE_BSRR       (volatile unsigned int *)(GPIOE + 0x18)
#define GPIOE_LCKR       (volatile unsigned int *)(GPIOE + 0x1c)
#define GPIOE_AFRL       (volatile unsigned int *)(GPIOE + 0x20)
#define GPIOE_AFRH       (volatile unsigned int *)(GPIOE + 0x24)

#define GPIOF_MODER      (volatile unsigned int *)(GPIOF + 0x00)
#define GPIOF_OTYPER     (volatile unsigned int *)(GPIOF + 0x04)
#define GPIOF_OSPEEDR    (volatile unsigned int *)(GPIOF + 0x08)
#define GPIOF_PUPDR      (volatile unsigned int *)(GPIOF + 0x0c)
#define GPIOF_IDR        (volatile unsigned int *)(GPIOF + 0x10)
#define GPIOF_ODR        (volatile unsigned int *)(GPIOF + 0x14)
#define GPIOF_BSRR       (volatile unsigned int *)(GPIOF + 0x18)
#define GPIOF_LCKR       (volatile unsigned int *)(GPIOF + 0x1c)
#define GPIOF_AFRL       (volatile unsigned int *)(GPIOF + 0x20)
#define GPIOF_AFRH       (volatile unsigned int *)(GPIOF + 0x24)

#endif

