
#ifndef TIMER_H
#define TIMER_H

#include "memory.h"

#define TIM1_CR1        ((volatile unsigned int *)(TIM1 + 0x00))
#define TIM1_CR2        ((volatile unsigned int *)(TIM1 + 0x04))
#define TIM1_SMCR       ((volatile unsigned int *)(TIM1 + 0x08))
#define TIM1_DIER       ((volatile unsigned int *)(TIM1 + 0x0C))
#define TIM1_SR         ((volatile unsigned int *)(TIM1 + 0x10))
#define TIM1_EGR        ((volatile unsigned int *)(TIM1 + 0x14))
#define TIM1_CCMR1      ((volatile unsigned int *)(TIM1 + 0x18))
#define TIM1_CCMR2      ((volatile unsigned int *)(TIM1 + 0x1C))
#define TIM1_CCER       ((volatile unsigned int *)(TIM1 + 0x20))
#define TIM1_CNT        ((volatile unsigned int *)(TIM1 + 0x24))
#define TIM1_PSC        ((volatile unsigned int *)(TIM1 + 0x28))
#define TIM1_ARR        ((volatile unsigned int *)(TIM1 + 0x2C))
#define TIM1_RCR        ((volatile unsigned int *)(TIM1 + 0x30))
#define TIM1_CCR1       ((volatile unsigned int *)(TIM1 + 0x34))
#define TIM1_CCR2       ((volatile unsigned int *)(TIM1 + 0x38))
#define TIM1_CCR3       ((volatile unsigned int *)(TIM1 + 0x3C))
#define TIM1_CCR4       ((volatile unsigned int *)(TIM1 + 0x40))
#define TIM1_BDTR       ((volatile unsigned int *)(TIM1 + 0x44))
#define TIM1_DCR        ((volatile unsigned int *)(TIM1 + 0x48))
#define TIM1_DMAR       ((volatile unsigned int *)(TIM1 + 0x4C))
#define TIM1_CCMR3      ((volatile unsigned int *)(TIM1 + 0x54))
#define TIM1_CCR5       ((volatile unsigned int *)(TIM1 + 0x58))
#define TIM1_CCR6       ((volatile unsigned int *)(TIM1 + 0x5c))
#define TIM1_AF1        ((volatile unsigned int *)(TIM1 + 0x60))
#define TIM1_AF2        ((volatile unsigned int *)(TIM1 + 0x64))
#define TIM1_TISEL      ((volatile unsigned int *)(TIM1 + 0x68))

#define TIM3_CR1        ((volatile unsigned int *)(TIM3 + 0x00))
#define TIM3_CR2        ((volatile unsigned int *)(TIM3 + 0x04))
#define TIM3_SMCR       ((volatile unsigned int *)(TIM3 + 0x08))
#define TIM3_DIER       ((volatile unsigned int *)(TIM3 + 0x0C))
#define TIM3_SR         ((volatile unsigned int *)(TIM3 + 0x10))
#define TIM3_EGR        ((volatile unsigned int *)(TIM3 + 0x14))
#define TIM3_CCMR1      ((volatile unsigned int *)(TIM3 + 0x18))
#define TIM3_CCMR2      ((volatile unsigned int *)(TIM3 + 0x1C))
#define TIM3_CCER       ((volatile unsigned int *)(TIM3 + 0x20))
#define TIM3_CNT        ((volatile unsigned int *)(TIM3 + 0x24))
#define TIM3_PSC        ((volatile unsigned int *)(TIM3 + 0x28))
#define TIM3_ARR        ((volatile unsigned int *)(TIM3 + 0x2C))
#define TIM3_RCR        ((volatile unsigned int *)(TIM3 + 0x30))
#define TIM3_CCR1       ((volatile unsigned int *)(TIM3 + 0x34))
#define TIM3_CCR2       ((volatile unsigned int *)(TIM3 + 0x38))
#define TIM3_CCR3       ((volatile unsigned int *)(TIM3 + 0x3C))
#define TIM3_CCR4       ((volatile unsigned int *)(TIM3 + 0x40))
#define TIM3_DCR        ((volatile unsigned int *)(TIM3 + 0x48))
#define TIM3_DMAR       ((volatile unsigned int *)(TIM3 + 0x4C))
#define TIM3_AF1        ((volatile unsigned int *)(TIM3 + 0x60))
#define TIM3_TISEL      ((volatile unsigned int *)(TIM3 + 0x68))

#define TIM4_CR1        ((volatile unsigned int *)(TIM4 + 0x00))
#define TIM4_CR2        ((volatile unsigned int *)(TIM4 + 0x04))
#define TIM4_SMCR       ((volatile unsigned int *)(TIM4 + 0x08))
#define TIM4_DIER       ((volatile unsigned int *)(TIM4 + 0x0C))
#define TIM4_SR         ((volatile unsigned int *)(TIM4 + 0x10))
#define TIM4_EGR        ((volatile unsigned int *)(TIM4 + 0x14))
#define TIM4_CCMR1      ((volatile unsigned int *)(TIM4 + 0x18))
#define TIM4_CCMR2      ((volatile unsigned int *)(TIM4 + 0x1C))
#define TIM4_CCER       ((volatile unsigned int *)(TIM4 + 0x20))
#define TIM4_CNT        ((volatile unsigned int *)(TIM4 + 0x24))
#define TIM4_PSC        ((volatile unsigned int *)(TIM4 + 0x28))
#define TIM4_ARR        ((volatile unsigned int *)(TIM4 + 0x2C))
#define TIM4_RCR        ((volatile unsigned int *)(TIM4 + 0x30))
#define TIM4_CCR1       ((volatile unsigned int *)(TIM4 + 0x34))
#define TIM4_CCR2       ((volatile unsigned int *)(TIM4 + 0x38))
#define TIM4_CCR3       ((volatile unsigned int *)(TIM4 + 0x3C))
#define TIM4_CCR4       ((volatile unsigned int *)(TIM4 + 0x40))
#define TIM4_DCR        ((volatile unsigned int *)(TIM4 + 0x48))
#define TIM4_DMAR       ((volatile unsigned int *)(TIM4 + 0x4C))
#define TIM4_AF1        ((volatile unsigned int *)(TIM4 + 0x60))
#define TIM4_TISEL      ((volatile unsigned int *)(TIM4 + 0x68))

#define TIM6_CR1        ((volatile unsigned int *)(TIM6 + 0x00))
#define TIM6_CR2        ((volatile unsigned int *)(TIM6 + 0x04))
#define TIM6_DIER       ((volatile unsigned int *)(TIM6 + 0x0C))
#define TIM6_SR         ((volatile unsigned int *)(TIM6 + 0x10))
#define TIM6_EGR        ((volatile unsigned int *)(TIM6 + 0x14))
#define TIM6_CNT        ((volatile unsigned int *)(TIM6 + 0x24))
#define TIM6_PSC        ((volatile unsigned int *)(TIM6 + 0x28))
#define TIM6_ARR        ((volatile unsigned int *)(TIM6 + 0x2C))

#define TIM7_CR1        ((volatile unsigned int *)(TIM7 + 0x00))
#define TIM7_CR2        ((volatile unsigned int *)(TIM7 + 0x04))
#define TIM7_DIER       ((volatile unsigned int *)(TIM7 + 0x0C))
#define TIM7_SR         ((volatile unsigned int *)(TIM7 + 0x10))
#define TIM7_EGR        ((volatile unsigned int *)(TIM7 + 0x14))
#define TIM7_CNT        ((volatile unsigned int *)(TIM7 + 0x24))
#define TIM7_PSC        ((volatile unsigned int *)(TIM7 + 0x28))
#define TIM7_ARR        ((volatile unsigned int *)(TIM7 + 0x2C))

#define TIM14_CR1       ((volatile unsigned int *)(TIM14 + 0x00))
#define TIM14_DIER      ((volatile unsigned int *)(TIM14 + 0x0C))
#define TIM14_SR        ((volatile unsigned int *)(TIM14 + 0x10))
#define TIM14_EGR       ((volatile unsigned int *)(TIM14 + 0x14))
#define TIM14_CCMR1     ((volatile unsigned int *)(TIM14 + 0x18))
#define TIM14_CCMR2     ((volatile unsigned int *)(TIM14 + 0x1C))
#define TIM14_CCER      ((volatile unsigned int *)(TIM14 + 0x20))
#define TIM14_CNT       ((volatile unsigned int *)(TIM14 + 0x24))
#define TIM14_PSC       ((volatile unsigned int *)(TIM14 + 0x28))
#define TIM14_ARR       ((volatile unsigned int *)(TIM14 + 0x2C))
#define TIM14_CCR1      ((volatile unsigned int *)(TIM14 + 0x34))
#define TIM14_TISEL     ((volatile unsigned int *)(TIM14 + 0x68))

#define TIM15_CR1       ((volatile unsigned int *)(TIM15 + 0x00))
#define TIM15_CR2       ((volatile unsigned int *)(TIM15 + 0x04))
#define TIM15_SMCR      ((volatile unsigned int *)(TIM15 + 0x08))
#define TIM15_DIER      ((volatile unsigned int *)(TIM15 + 0x0C))
#define TIM15_SR        ((volatile unsigned int *)(TIM15 + 0x10))
#define TIM15_EGR       ((volatile unsigned int *)(TIM15 + 0x14))
#define TIM15_CCMR1     ((volatile unsigned int *)(TIM15 + 0x18))
#define TIM15_CCER      ((volatile unsigned int *)(TIM15 + 0x20))
#define TIM15_CNT       ((volatile unsigned int *)(TIM15 + 0x24))
#define TIM15_PSC       ((volatile unsigned int *)(TIM15 + 0x28))
#define TIM15_ARR       ((volatile unsigned int *)(TIM15 + 0x2C))
#define TIM15_RCR       ((volatile unsigned int *)(TIM15 + 0x30))
#define TIM15_CCR1      ((volatile unsigned int *)(TIM15 + 0x34))
#define TIM15_CCR2      ((volatile unsigned int *)(TIM15 + 0x38))
#define TIM15_BDTR      ((volatile unsigned int *)(TIM15 + 0x44))
#define TIM15_DCR       ((volatile unsigned int *)(TIM15 + 0x48))
#define TIM15_DMAR      ((volatile unsigned int *)(TIM15 + 0x4C))
#define TIM15_AF1       ((volatile unsigned int *)(TIM15 + 0x60))
#define TIM15_TISEL     ((volatile unsigned int *)(TIM15 + 0x68))

#define TIM16_CR1       ((volatile unsigned int *)(TIM16 + 0x00))
#define TIM16_CR2       ((volatile unsigned int *)(TIM16 + 0x04))
#define TIM16_DIER      ((volatile unsigned int *)(TIM16 + 0x0C))
#define TIM16_SR        ((volatile unsigned int *)(TIM16 + 0x10))
#define TIM16_EGR       ((volatile unsigned int *)(TIM16 + 0x14))
#define TIM16_CCMR1     ((volatile unsigned int *)(TIM16 + 0x18))
#define TIM16_CCMR2     ((volatile unsigned int *)(TIM16 + 0x1C))
#define TIM16_CCER      ((volatile unsigned int *)(TIM16 + 0x20))
#define TIM16_CNT       ((volatile unsigned int *)(TIM16 + 0x24))
#define TIM16_PSC       ((volatile unsigned int *)(TIM16 + 0x28))
#define TIM16_ARR       ((volatile unsigned int *)(TIM16 + 0x2C))
#define TIM16_RCR       ((volatile unsigned int *)(TIM16 + 0x30))
#define TIM16_CCR1      ((volatile unsigned int *)(TIM16 + 0x34))
#define TIM16_BDTR      ((volatile unsigned int *)(TIM16 + 0x44))
#define TIM16_DCR       ((volatile unsigned int *)(TIM16 + 0x48))
#define TIM16_DMAR      ((volatile unsigned int *)(TIM16 + 0x4C))
#define TIM16_AF1       ((volatile unsigned int *)(TIM16 + 0x60))
#define TIM16_TISEL     ((volatile unsigned int *)(TIM16 + 0x68))

#define TIM17_CR1       ((volatile unsigned int *)(TIM17 + 0x00))
#define TIM17_CR2       ((volatile unsigned int *)(TIM17 + 0x04))
#define TIM17_DIER      ((volatile unsigned int *)(TIM17 + 0x0C))
#define TIM17_SR        ((volatile unsigned int *)(TIM17 + 0x10))
#define TIM17_EGR       ((volatile unsigned int *)(TIM17 + 0x14))
#define TIM17_CCMR1     ((volatile unsigned int *)(TIM17 + 0x18))
#define TIM17_CCMR2     ((volatile unsigned int *)(TIM17 + 0x1C))
#define TIM17_CCER      ((volatile unsigned int *)(TIM17 + 0x20))
#define TIM17_CNT       ((volatile unsigned int *)(TIM17 + 0x24))
#define TIM17_PSC       ((volatile unsigned int *)(TIM17 + 0x28))
#define TIM17_ARR       ((volatile unsigned int *)(TIM17 + 0x2C))
#define TIM17_RCR       ((volatile unsigned int *)(TIM17 + 0x30))
#define TIM17_CCR1      ((volatile unsigned int *)(TIM17 + 0x34))
#define TIM17_BDTR      ((volatile unsigned int *)(TIM17 + 0x44))
#define TIM17_DCR       ((volatile unsigned int *)(TIM17 + 0x48))
#define TIM17_DMAR      ((volatile unsigned int *)(TIM17 + 0x4C))
#define TIM17_AF1       ((volatile unsigned int *)(TIM17 + 0x60))
#define TIM17_TISEL     ((volatile unsigned int *)(TIM17 + 0x68))

#endif

