
#ifndef USART_UART_H
#define USART_UART_H

#include "memory.h"

#define USART1_CR1 (volatile unsigned int *)(USART1 + 0x00)
#define USART1_CR2 (volatile unsigned int *)(USART1 + 0x04)
#define USART1_CR3 (volatile unsigned int *)(USART1 + 0x08)
#define USART1_BRR (volatile unsigned int *)(USART1 + 0x0C)
#define USART1_GTPR (volatile unsigned int *)(USART1 + 0x10)
#define USART1_RTOR (volatile unsigned int *)(USART1 + 0x14)
#define USART1_RQR (volatile unsigned int *)(USART1 + 0x18)
#define USART1_ISR (volatile unsigned int *)(USART1 + 0x1C)
#define USART1_ICR (volatile unsigned int *)(USART1 + 0x20)
#define USART1_RDR (volatile unsigned int *)(USART1 + 0x24)
#define USART1_TDR (volatile unsigned int *)(USART1 + 0x28)
#define USART1_PRESC (volatile unsigned int *)(USART1 + 0x2C)

#define USART2_CR1 (volatile unsigned int *)(USART2 + 0x00)
#define USART2_CR2 (volatile unsigned int *)(USART2 + 0x04)
#define USART2_CR3 (volatile unsigned int *)(USART2 + 0x08)
#define USART2_BRR (volatile unsigned int *)(USART2 + 0x0C)
#define USART2_GTPR (volatile unsigned int *)(USART2 + 0x10)
#define USART2_RTOR (volatile unsigned int *)(USART2 + 0x14)
#define USART2_RQR (volatile unsigned int *)(USART2 + 0x18)
#define USART2_ISR (volatile unsigned int *)(USART2 + 0x1C)
#define USART2_ICR (volatile unsigned int *)(USART2 + 0x20)
#define USART2_RDR (volatile unsigned int *)(USART2 + 0x24)
#define USART2_TDR (volatile unsigned int *)(USART2 + 0x28)
#define USART2_PRESC (volatile unsigned int *)(USART2 + 0x2C)

#define USART3_CR1 (volatile unsigned int *)(USART3 + 0x00)
#define USART3_CR2 (volatile unsigned int *)(USART3 + 0x04)
#define USART3_CR3 (volatile unsigned int *)(USART3 + 0x08)
#define USART3_BRR (volatile unsigned int *)(USART3 + 0x0C)
#define USART3_GTPR (volatile unsigned int *)(USART3 + 0x10)
#define USART3_RTOR (volatile unsigned int *)(USART3 + 0x14)
#define USART3_RQR (volatile unsigned int *)(USART3 + 0x18)
#define USART3_ISR (volatile unsigned int *)(USART3 + 0x1C)
#define USART3_ICR (volatile unsigned int *)(USART3 + 0x20)
#define USART3_RDR (volatile unsigned int *)(USART3 + 0x24)
#define USART3_TDR (volatile unsigned int *)(USART3 + 0x28)
#define USART3_PRESC (volatile unsigned int *)(USART3 + 0x2C)

#define USART4_CR1 (volatile unsigned int *)(USART4 + 0x00)
#define USART4_CR2 (volatile unsigned int *)(USART4 + 0x04)
#define USART4_CR3 (volatile unsigned int *)(USART4 + 0x08)
#define USART4_BRR (volatile unsigned int *)(USART4 + 0x0C)
#define USART4_GTPR (volatile unsigned int *)(USART4 + 0x10)
#define USART4_RTOR (volatile unsigned int *)(USART4 + 0x14)
#define USART4_RQR (volatile unsigned int *)(USART4 + 0x18)
#define USART4_ISR (volatile unsigned int *)(USART4 + 0x1C)
#define USART4_ICR (volatile unsigned int *)(USART4 + 0x20)
#define USART4_RDR (volatile unsigned int *)(USART4 + 0x24)
#define USART4_TDR (volatile unsigned int *)(USART4 + 0x28)
#define USART4_PRESC (volatile unsigned int *)(USART4 + 0x2C)

#define USART5_CR1 (volatile unsigned int *)(USART5 + 0x00)
#define USART5_CR2 (volatile unsigned int *)(USART5 + 0x04)
#define USART5_CR3 (volatile unsigned int *)(USART5 + 0x08)
#define USART5_BRR (volatile unsigned int *)(USART5 + 0x0C)
#define USART5_GTPR (volatile unsigned int *)(USART5 + 0x10)
#define USART5_RTOR (volatile unsigned int *)(USART5 + 0x14)
#define USART5_RQR (volatile unsigned int *)(USART5 + 0x18)
#define USART5_ISR (volatile unsigned int *)(USART5 + 0x1C)
#define USART5_ICR (volatile unsigned int *)(USART5 + 0x20)
#define USART5_RDR (volatile unsigned int *)(USART5 + 0x24)
#define USART5_TDR (volatile unsigned int *)(USART5 + 0x28)
#define USART5_PRESC (volatile unsigned int *)(USART5 + 0x2C)

#define USART6_CR1 (volatile unsigned int *)(USART6 + 0x00)
#define USART6_CR2 (volatile unsigned int *)(USART6 + 0x04)
#define USART6_CR3 (volatile unsigned int *)(USART6 + 0x08)
#define USART6_BRR (volatile unsigned int *)(USART6 + 0x0C)
#define USART6_GTPR (volatile unsigned int *)(USART6 + 0x10)
#define USART6_RTOR (volatile unsigned int *)(USART6 + 0x14)
#define USART6_RQR (volatile unsigned int *)(USART6 + 0x18)
#define USART6_ISR (volatile unsigned int *)(USART6 + 0x1C)
#define USART6_ICR (volatile unsigned int *)(USART6 + 0x20)
#define USART6_RDR (volatile unsigned int *)(USART6 + 0x24)
#define USART6_TDR (volatile unsigned int *)(USART6 + 0x28)
#define USART6_PRESC (volatile unsigned int *)(USART6 + 0x2C)

#endif

