
#ifndef DMA_H
#define DMA_H

/*
(from ST reference manual RM0433 Rev 8)
DMA low interrupt status register (DMA_LISR) Address offset: 0x000
DMA high interrupt status register (DMA_HISR) Address offset: 0x004
DMA low interrupt flag clear register (DMA_LIFCR) Address offset: 0x008
DMA high interrupt flag clear register (DMA_HIFCR) Address offset: 0x00C
DMA stream x configuration register (DMA_SxCR) Address offset: 0x010 + 0x18 * x, (x = 0 to 7)
DMA stream x number of data register (DMA_SxNDTR) Address offset: 0x014 + 0x18 * x, (x = 0 to 7)
DMA stream x peripheral address register (DMA_SxPAR) Address offset: 0x018 + 0x18 * x, (x = 0 to 7)
DMA stream x memory 0 address register (DMA_SxM0AR) Address offset: 0x01C + 0x18 * x, (x = 0 to 7)
DMA stream x memory 1 address register (DMA_SxM1AR) Address offset: 0x020 + 0x18 * x, (x = 0 to 7)
DMA stream x FIFO control register (DMA_SxFCR) Address offset: 0x024 + 0x18 * x, (x = 0 to 7)
*/

#define DMA1_LISR         (volatile unsigned int *)(DMA1 + 0x000)
#define DMA1_HISR         (volatile unsigned int *)(DMA1 + 0x004)
#define DMA1_LIFCR        (volatile unsigned int *)(DMA1 + 0x008)
#define DMA1_HIFCR        (volatile unsigned int *)(DMA1 + 0x00c)
#define DMA1_S0CR         (volatile unsigned int *)(DMA1 + 0x010)
#define DMA1_S0NDTR       (volatile unsigned int *)(DMA1 + 0x014)
#define DMA1_S0PAR        (volatile unsigned int *)(DMA1 + 0x018)
#define DMA1_S0M0AR       (volatile unsigned int *)(DMA1 + 0x01c)
#define DMA1_S0M1AR       (volatile unsigned int *)(DMA1 + 0x020)
#define DMA1_S0FCR        (volatile unsigned int *)(DMA1 + 0x024)
#define DMA1_S1CR         (volatile unsigned int *)(DMA1 + 0x028)
#define DMA1_S1NDTR       (volatile unsigned int *)(DMA1 + 0x02c)
#define DMA1_S1PAR        (volatile unsigned int *)(DMA1 + 0x030)
#define DMA1_S1M0AR       (volatile unsigned int *)(DMA1 + 0x034)
#define DMA1_S1M1AR       (volatile unsigned int *)(DMA1 + 0x038)
#define DMA1_S1FCR        (volatile unsigned int *)(DMA1 + 0x03c)
#define DMA1_S2CR         (volatile unsigned int *)(DMA1 + 0x040)
#define DMA1_S2NDTR       (volatile unsigned int *)(DMA1 + 0x044)
#define DMA1_S2PAR        (volatile unsigned int *)(DMA1 + 0x048)
#define DMA1_S2M0AR       (volatile unsigned int *)(DMA1 + 0x04c)
#define DMA1_S2M1AR       (volatile unsigned int *)(DMA1 + 0x050)
#define DMA1_S2FCR        (volatile unsigned int *)(DMA1 + 0x054)
#define DMA1_S3CR         (volatile unsigned int *)(DMA1 + 0x058)
#define DMA1_S3NDTR       (volatile unsigned int *)(DMA1 + 0x05c)
#define DMA1_S3PAR        (volatile unsigned int *)(DMA1 + 0x060)
#define DMA1_S3M0AR       (volatile unsigned int *)(DMA1 + 0x064)
#define DMA1_S3M1AR       (volatile unsigned int *)(DMA1 + 0x068)
#define DMA1_S3FCR        (volatile unsigned int *)(DMA1 + 0x06c)
#define DMA1_S4CR         (volatile unsigned int *)(DMA1 + 0x070)
#define DMA1_S4NDTR       (volatile unsigned int *)(DMA1 + 0x074)
#define DMA1_S4PAR        (volatile unsigned int *)(DMA1 + 0x078)
#define DMA1_S4M0AR       (volatile unsigned int *)(DMA1 + 0x07c)
#define DMA1_S4M1AR       (volatile unsigned int *)(DMA1 + 0x080)
#define DMA1_S4FCR        (volatile unsigned int *)(DMA1 + 0x084)
#define DMA1_S5CR         (volatile unsigned int *)(DMA1 + 0x088)
#define DMA1_S5NDTR       (volatile unsigned int *)(DMA1 + 0x08c)
#define DMA1_S5PAR        (volatile unsigned int *)(DMA1 + 0x090)
#define DMA1_S5M0AR       (volatile unsigned int *)(DMA1 + 0x094)
#define DMA1_S5M1AR       (volatile unsigned int *)(DMA1 + 0x098)
#define DMA1_S5FCR        (volatile unsigned int *)(DMA1 + 0x09c)
#define DMA1_S6CR         (volatile unsigned int *)(DMA1 + 0x0a0)
#define DMA1_S6NDTR       (volatile unsigned int *)(DMA1 + 0x0a4)
#define DMA1_S6PAR        (volatile unsigned int *)(DMA1 + 0x0a8)
#define DMA1_S6M0AR       (volatile unsigned int *)(DMA1 + 0x0ac)
#define DMA1_S6M1AR       (volatile unsigned int *)(DMA1 + 0x0b0)
#define DMA1_S6FCR        (volatile unsigned int *)(DMA1 + 0x0b4)
#define DMA1_S7CR         (volatile unsigned int *)(DMA1 + 0x0b8)
#define DMA1_S7NDTR       (volatile unsigned int *)(DMA1 + 0x0bc)
#define DMA1_S7PAR        (volatile unsigned int *)(DMA1 + 0x0c0)
#define DMA1_S7M0AR       (volatile unsigned int *)(DMA1 + 0x0c4)
#define DMA1_S7M1AR       (volatile unsigned int *)(DMA1 + 0x0c8)
#define DMA1_S7FCR        (volatile unsigned int *)(DMA1 + 0x0cc)

#define DMA2_LISR         (volatile unsigned int *)(DMA2 + 0x000)
#define DMA2_HISR         (volatile unsigned int *)(DMA2 + 0x004)
#define DMA2_LIFCR        (volatile unsigned int *)(DMA2 + 0x008)
#define DMA2_HIFCR        (volatile unsigned int *)(DMA2 + 0x00c)
#define DMA2_S0CR         (volatile unsigned int *)(DMA2 + 0x010)
#define DMA2_S0NDTR       (volatile unsigned int *)(DMA2 + 0x014)
#define DMA2_S0PAR        (volatile unsigned int *)(DMA2 + 0x018)
#define DMA2_S0M0AR       (volatile unsigned int *)(DMA2 + 0x01c)
#define DMA2_S0M1AR       (volatile unsigned int *)(DMA2 + 0x020)
#define DMA2_S0FCR        (volatile unsigned int *)(DMA2 + 0x024)
#define DMA2_S1CR         (volatile unsigned int *)(DMA2 + 0x028)
#define DMA2_S1NDTR       (volatile unsigned int *)(DMA2 + 0x02c)
#define DMA2_S1PAR        (volatile unsigned int *)(DMA2 + 0x030)
#define DMA2_S1M0AR       (volatile unsigned int *)(DMA2 + 0x034)
#define DMA2_S1M1AR       (volatile unsigned int *)(DMA2 + 0x038)
#define DMA2_S1FCR        (volatile unsigned int *)(DMA2 + 0x03c)
#define DMA2_S2CR         (volatile unsigned int *)(DMA2 + 0x040)
#define DMA2_S2NDTR       (volatile unsigned int *)(DMA2 + 0x044)
#define DMA2_S2PAR        (volatile unsigned int *)(DMA2 + 0x048)
#define DMA2_S2M0AR       (volatile unsigned int *)(DMA2 + 0x04c)
#define DMA2_S2M1AR       (volatile unsigned int *)(DMA2 + 0x050)
#define DMA2_S2FCR        (volatile unsigned int *)(DMA2 + 0x054)
#define DMA2_S3CR         (volatile unsigned int *)(DMA2 + 0x058)
#define DMA2_S3NDTR       (volatile unsigned int *)(DMA2 + 0x05c)
#define DMA2_S3PAR        (volatile unsigned int *)(DMA2 + 0x060)
#define DMA2_S3M0AR       (volatile unsigned int *)(DMA2 + 0x064)
#define DMA2_S3M1AR       (volatile unsigned int *)(DMA2 + 0x068)
#define DMA2_S3FCR        (volatile unsigned int *)(DMA2 + 0x06c)
#define DMA2_S4CR         (volatile unsigned int *)(DMA2 + 0x070)
#define DMA2_S4NDTR       (volatile unsigned int *)(DMA2 + 0x074)
#define DMA2_S4PAR        (volatile unsigned int *)(DMA2 + 0x078)
#define DMA2_S4M0AR       (volatile unsigned int *)(DMA2 + 0x07c)
#define DMA2_S4M1AR       (volatile unsigned int *)(DMA2 + 0x080)
#define DMA2_S4FCR        (volatile unsigned int *)(DMA2 + 0x084)
#define DMA2_S5CR         (volatile unsigned int *)(DMA2 + 0x088)
#define DMA2_S5NDTR       (volatile unsigned int *)(DMA2 + 0x08c)
#define DMA2_S5PAR        (volatile unsigned int *)(DMA2 + 0x090)
#define DMA2_S5M0AR       (volatile unsigned int *)(DMA2 + 0x094)
#define DMA2_S5M1AR       (volatile unsigned int *)(DMA2 + 0x098)
#define DMA2_S5FCR        (volatile unsigned int *)(DMA2 + 0x09c)
#define DMA2_S6CR         (volatile unsigned int *)(DMA2 + 0x0a0)
#define DMA2_S6NDTR       (volatile unsigned int *)(DMA2 + 0x0a4)
#define DMA2_S6PAR        (volatile unsigned int *)(DMA2 + 0x0a8)
#define DMA2_S6M0AR       (volatile unsigned int *)(DMA2 + 0x0ac)
#define DMA2_S6M1AR       (volatile unsigned int *)(DMA2 + 0x0b0)
#define DMA2_S6FCR        (volatile unsigned int *)(DMA2 + 0x0b4)
#define DMA2_S7CR         (volatile unsigned int *)(DMA2 + 0x0b8)
#define DMA2_S7NDTR       (volatile unsigned int *)(DMA2 + 0x0bc)
#define DMA2_S7PAR        (volatile unsigned int *)(DMA2 + 0x0c0)
#define DMA2_S7M0AR       (volatile unsigned int *)(DMA2 + 0x0c4)
#define DMA2_S7M1AR       (volatile unsigned int *)(DMA2 + 0x0c8)
#define DMA2_S7FCR        (volatile unsigned int *)(DMA2 + 0x0cc)

#endif
