#ifndef SDMMC_h
#define SDMMC_h

#define SDMMC1_POWER       (volatile unsigned int *)(SDMMC1 + 0x00u)
#define SDMMC1_CLKCR       (volatile unsigned int *)(SDMMC1 + 0x04u)
#define SDMMC1_ARGR        (volatile unsigned int *)(SDMMC1 + 0x08u)
#define SDMMC1_CMDR        (volatile unsigned int *)(SDMMC1 + 0x0cu)
#define SDMMC1_RESPCMDR    (volatile unsigned int *)(SDMMC1 + 0x10u)
#define SDMMC1_RESP1R      (volatile unsigned int *)(SDMMC1 + 0x14u)
#define SDMMC1_RESP2R      (volatile unsigned int *)(SDMMC1 + 0x18u)
#define SDMMC1_RESP3R      (volatile unsigned int *)(SDMMC1 + 0x1cu)
#define SDMMC1_RESP4R      (volatile unsigned int *)(SDMMC1 + 0x20u)
#define SDMMC1_DTIMER      (volatile unsigned int *)(SDMMC1 + 0x24u)
#define SDMMC1_DLENR       (volatile unsigned int *)(SDMMC1 + 0x28u)
#define SDMMC1_DCTRL       (volatile unsigned int *)(SDMMC1 + 0x2cu)
#define SDMMC1_DCNTR       (volatile unsigned int *)(SDMMC1 + 0x30u)
#define SDMMC1_STAR        (volatile unsigned int *)(SDMMC1 + 0x34u)
#define SDMMC1_ICR         (volatile unsigned int *)(SDMMC1 + 0x38u)
#define SDMMC1_MASKR       (volatile unsigned int *)(SDMMC1 + 0x3cu)
#define SDMMC1_ACKTIMER    (volatile unsigned int *)(SDMMC1 + 0x40u)
#define SDMMC1_IDMACTRLR   (volatile unsigned int *)(SDMMC1 + 0x50u)
#define SDMMC1_IDMABSIZER  (volatile unsigned int *)(SDMMC1 + 0x54u)
#define SDMMC1_IDMABASE0R  (volatile unsigned int *)(SDMMC1 + 0x58u)
#define SDMMC1_IDMABASE1R  (volatile unsigned int *)(SDMMC1 + 0x5cu)
#define SDMMC1_FIFOR       (volatile unsigned int *)(SDMMC1 + 0x80u)

#define SDMMC2_POWER       (volatile unsigned int *)(SDMMC2 + 0x00u)
#define SDMMC2_CLKCR       (volatile unsigned int *)(SDMMC2 + 0x04u)
#define SDMMC2_ARGR        (volatile unsigned int *)(SDMMC2 + 0x08u)
#define SDMMC2_CMDR        (volatile unsigned int *)(SDMMC2 + 0x0cu)
#define SDMMC2_RESPCMDR    (volatile unsigned int *)(SDMMC2 + 0x10u)
#define SDMMC2_RESP1R      (volatile unsigned int *)(SDMMC2 + 0x14u)
#define SDMMC2_RESP2R      (volatile unsigned int *)(SDMMC2 + 0x18u)
#define SDMMC2_RESP3R      (volatile unsigned int *)(SDMMC2 + 0x1cu)
#define SDMMC2_RESP4R      (volatile unsigned int *)(SDMMC2 + 0x20u)
#define SDMMC2_DTIMER      (volatile unsigned int *)(SDMMC2 + 0x24u)
#define SDMMC2_DLENR       (volatile unsigned int *)(SDMMC2 + 0x28u)
#define SDMMC2_DCTRL       (volatile unsigned int *)(SDMMC2 + 0x2cu)
#define SDMMC2_DCNTR       (volatile unsigned int *)(SDMMC2 + 0x30u)
#define SDMMC2_STAR        (volatile unsigned int *)(SDMMC2 + 0x34u)
#define SDMMC2_ICR         (volatile unsigned int *)(SDMMC2 + 0x38u)
#define SDMMC2_MASKR       (volatile unsigned int *)(SDMMC2 + 0x3cu)
#define SDMMC2_ACKTIMER    (volatile unsigned int *)(SDMMC2 + 0x40u)
#define SDMMC2_IDMACTRLR   (volatile unsigned int *)(SDMMC2 + 0x50u)
#define SDMMC2_IDMABSIZER  (volatile unsigned int *)(SDMMC2 + 0x54u)
#define SDMMC2_IDMABASE0R  (volatile unsigned int *)(SDMMC2 + 0x58u)
#define SDMMC2_IDMABASE1R  (volatile unsigned int *)(SDMMC2 + 0x5cu)
#define SDMMC2_FIFOR       (volatile unsigned int *)(SDMMC2 + 0x80u)

#endif
