#ifndef SPI_I2S_h
#define SPI_I2S_h

#include "memory.h"

#define SPI1_CR1           (volatile unsigned int*)(SPI1 + 0x00)
#define SPI1_CR2           (volatile unsigned int*)(SPI1 + 0x04)
#define SPI1_CFG1          (volatile unsigned int*)(SPI1 + 0x08)
#define SPI1_CFG2          (volatile unsigned int*)(SPI1 + 0x0c)
#define SPI1_IER           (volatile unsigned int*)(SPI1 + 0x10)
#define SPI1_SR            (volatile unsigned int*)(SPI1 + 0x14)
#define SPI1_IFCR          (volatile unsigned int*)(SPI1 + 0x18)
#define SPI1_TXDR          (volatile unsigned int*)(SPI1 + 0x20)
#define SPI1_RXDR          (volatile unsigned int*)(SPI1 + 0x30)
#define SPI1_CRCPOLY       (volatile unsigned int*)(SPI1 + 0x40)
#define SPI1_TXCRC         (volatile unsigned int*)(SPI1 + 0x44)
#define SPI1_RXCRC         (volatile unsigned int*)(SPI1 + 0x48)
#define SPI1_UDRDR         (volatile unsigned int*)(SPI1 + 0x4c)
#define SPI1_I2SCFGR       (volatile unsigned int*)(SPI1 + 0x50)

#define SPI2_CR1           (volatile unsigned int*)(SPI2 + 0x00)
#define SPI2_CR2           (volatile unsigned int*)(SPI2 + 0x04)
#define SPI2_CFG1          (volatile unsigned int*)(SPI2 + 0x08)
#define SPI2_CFG2          (volatile unsigned int*)(SPI2 + 0x0c)
#define SPI2_IER           (volatile unsigned int*)(SPI2 + 0x10)
#define SPI2_SR            (volatile unsigned int*)(SPI2 + 0x14)
#define SPI2_IFCR          (volatile unsigned int*)(SPI2 + 0x18)
#define SPI2_TXDR          (volatile unsigned int*)(SPI2 + 0x20)
#define SPI2_RXDR          (volatile unsigned int*)(SPI2 + 0x30)
#define SPI2_CRCPOLY       (volatile unsigned int*)(SPI2 + 0x40)
#define SPI2_TXCRC         (volatile unsigned int*)(SPI2 + 0x44)
#define SPI2_RXCRC         (volatile unsigned int*)(SPI2 + 0x48)
#define SPI2_UDRDR         (volatile unsigned int*)(SPI2 + 0x4c)
#define SPI2_I2SCFGR       (volatile unsigned int*)(SPI2 + 0x50)

#define SPI3_CR1           (volatile unsigned int*)(SPI3 + 0x00)
#define SPI3_CR2           (volatile unsigned int*)(SPI3 + 0x04)
#define SPI3_CFG1          (volatile unsigned int*)(SPI3 + 0x08)
#define SPI3_CFG2          (volatile unsigned int*)(SPI3 + 0x0c)
#define SPI3_IER           (volatile unsigned int*)(SPI3 + 0x10)
#define SPI3_SR            (volatile unsigned int*)(SPI3 + 0x14)
#define SPI3_IFCR          (volatile unsigned int*)(SPI3 + 0x18)
#define SPI3_TXDR          (volatile unsigned int*)(SPI3 + 0x20)
#define SPI3_RXDR          (volatile unsigned int*)(SPI3 + 0x30)
#define SPI3_CRCPOLY       (volatile unsigned int*)(SPI3 + 0x40)
#define SPI3_TXCRC         (volatile unsigned int*)(SPI3 + 0x44)
#define SPI3_RXCRC         (volatile unsigned int*)(SPI3 + 0x48)
#define SPI3_UDRDR         (volatile unsigned int*)(SPI3 + 0x4c)
#define SPI3_I2SCFGR       (volatile unsigned int*)(SPI3 + 0x50)

#define SPI4_CR1           (volatile unsigned int*)(SPI4 + 0x00)
#define SPI4_CR2           (volatile unsigned int*)(SPI4 + 0x04)
#define SPI4_CFG1          (volatile unsigned int*)(SPI4 + 0x08)
#define SPI4_CFG2          (volatile unsigned int*)(SPI4 + 0x0c)
#define SPI4_IER           (volatile unsigned int*)(SPI4 + 0x10)
#define SPI4_SR            (volatile unsigned int*)(SPI4 + 0x14)
#define SPI4_IFCR          (volatile unsigned int*)(SPI4 + 0x18)
#define SPI4_TXDR          (volatile unsigned int*)(SPI4 + 0x20)
#define SPI4_RXDR          (volatile unsigned int*)(SPI4 + 0x30)
#define SPI4_CRCPOLY       (volatile unsigned int*)(SPI4 + 0x40)
#define SPI4_TXCRC         (volatile unsigned int*)(SPI4 + 0x44)
#define SPI4_RXCRC         (volatile unsigned int*)(SPI4 + 0x48)
#define SPI4_UDRDR         (volatile unsigned int*)(SPI4 + 0x4c)
#define SPI4_I2SCFGR       (volatile unsigned int*)(SPI4 + 0x50)

#define SPI5_CR1           (volatile unsigned int*)(SPI5 + 0x00)
#define SPI5_CR2           (volatile unsigned int*)(SPI5 + 0x04)
#define SPI5_CFG1          (volatile unsigned int*)(SPI5 + 0x08)
#define SPI5_CFG2          (volatile unsigned int*)(SPI5 + 0x0c)
#define SPI5_IER           (volatile unsigned int*)(SPI5 + 0x10)
#define SPI5_SR            (volatile unsigned int*)(SPI5 + 0x14)
#define SPI5_IFCR          (volatile unsigned int*)(SPI5 + 0x18)
#define SPI5_TXDR          (volatile unsigned int*)(SPI5 + 0x20)
#define SPI5_RXDR          (volatile unsigned int*)(SPI5 + 0x30)
#define SPI5_CRCPOLY       (volatile unsigned int*)(SPI5 + 0x40)
#define SPI5_TXCRC         (volatile unsigned int*)(SPI5 + 0x44)
#define SPI5_RXCRC         (volatile unsigned int*)(SPI5 + 0x48)
#define SPI5_UDRDR         (volatile unsigned int*)(SPI5 + 0x4c)
#define SPI5_I2SCFGR       (volatile unsigned int*)(SPI5 + 0x50)

#define SPI6_CR1           (volatile unsigned int*)(SPI6 + 0x00)
#define SPI6_CR2           (volatile unsigned int*)(SPI6 + 0x04)
#define SPI6_CFG1          (volatile unsigned int*)(SPI6 + 0x08)
#define SPI6_CFG2          (volatile unsigned int*)(SPI6 + 0x0c)
#define SPI6_IER           (volatile unsigned int*)(SPI6 + 0x10)
#define SPI6_SR            (volatile unsigned int*)(SPI6 + 0x14)
#define SPI6_IFCR          (volatile unsigned int*)(SPI6 + 0x18)
#define SPI6_TXDR          (volatile unsigned int*)(SPI6 + 0x20)
#define SPI6_RXDR          (volatile unsigned int*)(SPI6 + 0x30)
#define SPI6_CRCPOLY       (volatile unsigned int*)(SPI6 + 0x40)
#define SPI6_TXCRC         (volatile unsigned int*)(SPI6 + 0x44)
#define SPI6_RXCRC         (volatile unsigned int*)(SPI6 + 0x48)
#define SPI6_UDRDR         (volatile unsigned int*)(SPI6 + 0x4c)
#define SPI6_I2SCFGR       (volatile unsigned int*)(SPI6 + 0x50)

#endif
