
#ifndef TIMER_H
#define TIMER_H

#include "memory.h"

/* TODO: TIM15/TIM16/TIM17 etc */

#define TIM1_CR1   (volatile unsigned int *)(TIM1 + 0x00) 
#define TIM1_CR2   (volatile unsigned int *)(TIM1 + 0x04) 
#define TIM1_SMCR  (volatile unsigned int *)(TIM1 + 0x08) 
#define TIM1_DIER  (volatile unsigned int *)(TIM1 + 0x0c) 
#define TIM1_SR    (volatile unsigned int *)(TIM1 + 0x10) 
#define TIM1_EGR   (volatile unsigned int *)(TIM1 + 0x14) 
#define TIM1_CCMR1 (volatile unsigned int *)(TIM1 + 0x18) 
#define TIM1_CCMR2 (volatile unsigned int *)(TIM1 + 0x1c) 
#define TIM1_CCER  (volatile unsigned int *)(TIM1 + 0x20) 
#define TIM1_CNT   (volatile unsigned int *)(TIM1 + 0x24) 
#define TIM1_PSC   (volatile unsigned int *)(TIM1 + 0x28) 
#define TIM1_ARR   (volatile unsigned int *)(TIM1 + 0x2c) 
#define TIM1_RCR   (volatile unsigned int *)(TIM1 + 0x30) 
#define TIM1_CCR1  (volatile unsigned int *)(TIM1 + 0x34) 
#define TIM1_CCR2  (volatile unsigned int *)(TIM1 + 0x38) 
#define TIM1_CCR3  (volatile unsigned int *)(TIM1 + 0x3c) 
#define TIM1_CCR4  (volatile unsigned int *)(TIM1 + 0x40) 
#define TIM1_BDTR  (volatile unsigned int *)(TIM1 + 0x44) 
#define TIM1_DCR   (volatile unsigned int *)(TIM1 + 0x48) 
#define TIM1_DMAR  (volatile unsigned int *)(TIM1 + 0x4c) 
#define TIM1_CCMR3 (volatile unsigned int *)(TIM1 + 0x54) 
#define TIM1_CCR5  (volatile unsigned int *)(TIM1 + 0x58) 
#define TIM1_CCR6  (volatile unsigned int *)(TIM1 + 0x5c) 
#define TIM1_AF1   (volatile unsigned int *)(TIM1 + 0x60) 
#define TIM1_AF2   (volatile unsigned int *)(TIM1 + 0x64) 
#define TIM1_TISEL (volatile unsigned int *)(TIM1 + 0x68) 

#define TIM6_CR1   (volatile unsigned int *)(TIM6 + 0x00) 
#define TIM6_CR2   (volatile unsigned int *)(TIM6 + 0x04) 
#define TIM6_SMCR  (volatile unsigned int *)(TIM6 + 0x08) 
#define TIM6_DIER  (volatile unsigned int *)(TIM6 + 0x0c) 
#define TIM6_SR    (volatile unsigned int *)(TIM6 + 0x10) 
#define TIM6_EGR   (volatile unsigned int *)(TIM6 + 0x14) 
#define TIM6_CCMR1 (volatile unsigned int *)(TIM6 + 0x18) 
#define TIM6_CCMR2 (volatile unsigned int *)(TIM6 + 0x1c) 
#define TIM6_CCER  (volatile unsigned int *)(TIM6 + 0x20) 
#define TIM6_CNT   (volatile unsigned int *)(TIM6 + 0x24) 
#define TIM6_PSC   (volatile unsigned int *)(TIM6 + 0x28) 
#define TIM6_ARR   (volatile unsigned int *)(TIM6 + 0x2c) 
#define TIM6_RCR   (volatile unsigned int *)(TIM6 + 0x30) 
#define TIM6_CCR1  (volatile unsigned int *)(TIM6 + 0x34) 
#define TIM6_CCR2  (volatile unsigned int *)(TIM6 + 0x38) 
#define TIM6_CCR3  (volatile unsigned int *)(TIM6 + 0x3c) 
#define TIM6_CCR4  (volatile unsigned int *)(TIM6 + 0x40) 
#define TIM6_BDTR  (volatile unsigned int *)(TIM6 + 0x44) 
#define TIM6_DCR   (volatile unsigned int *)(TIM6 + 0x48) 
#define TIM6_DMAR  (volatile unsigned int *)(TIM6 + 0x4c) 
#define TIM6_CCMR3 (volatile unsigned int *)(TIM6 + 0x54) 
#define TIM6_CCR5  (volatile unsigned int *)(TIM6 + 0x58) 
#define TIM6_CCR6  (volatile unsigned int *)(TIM6 + 0x5c) 
#define TIM6_AF1   (volatile unsigned int *)(TIM6 + 0x60) 
#define TIM6_AF2   (volatile unsigned int *)(TIM6 + 0x64) 
#define TIM6_TISEL (volatile unsigned int *)(TIM6 + 0x68) 

#define TIM2_CR1   (volatile unsigned int *)(TIM2 + 0x00) 
#define TIM2_CR2   (volatile unsigned int *)(TIM2 + 0x04) 
#define TIM2_SMCR  (volatile unsigned int *)(TIM2 + 0x08) 
#define TIM2_DIER  (volatile unsigned int *)(TIM2 + 0x0c) 
#define TIM2_SR    (volatile unsigned int *)(TIM2 + 0x10) 
#define TIM2_EGR   (volatile unsigned int *)(TIM2 + 0x14) 
#define TIM2_CCMR1 (volatile unsigned int *)(TIM2 + 0x18) 
#define TIM2_CCMR2 (volatile unsigned int *)(TIM2 + 0x1c) 
#define TIM2_CCER  (volatile unsigned int *)(TIM2 + 0x20) 
#define TIM2_CNT   (volatile unsigned int *)(TIM2 + 0x24) 
#define TIM2_PSC   (volatile unsigned int *)(TIM2 + 0x28) 
#define TIM2_ARR   (volatile unsigned int *)(TIM2 + 0x2c) 
#define TIM2_RCR   (volatile unsigned int *)(TIM2 + 0x30) 
#define TIM2_CCR1  (volatile unsigned int *)(TIM2 + 0x34) 
#define TIM2_CCR2  (volatile unsigned int *)(TIM2 + 0x38) 
#define TIM2_CCR3  (volatile unsigned int *)(TIM2 + 0x3c) 
#define TIM2_CCR4  (volatile unsigned int *)(TIM2 + 0x40) 
#define TIM2_DCR   (volatile unsigned int *)(TIM2 + 0x48) 
#define TIM2_DMAR  (volatile unsigned int *)(TIM2 + 0x4c) 
#define TIM2_AF1   (volatile unsigned int *)(TIM2 + 0x60) 
#define TIM2_AF2   (volatile unsigned int *)(TIM2 + 0x64) 
#define TIM2_TISEL (volatile unsigned int *)(TIM2 + 0x68) 

#define TIM3_CR1   (volatile unsigned int *)(TIM3 + 0x00) 
#define TIM3_CR2   (volatile unsigned int *)(TIM3 + 0x04) 
#define TIM3_SMCR  (volatile unsigned int *)(TIM3 + 0x08) 
#define TIM3_DIER  (volatile unsigned int *)(TIM3 + 0x0c) 
#define TIM3_SR    (volatile unsigned int *)(TIM3 + 0x10) 
#define TIM3_EGR   (volatile unsigned int *)(TIM3 + 0x14) 
#define TIM3_CCMR1 (volatile unsigned int *)(TIM3 + 0x18) 
#define TIM3_CCMR2 (volatile unsigned int *)(TIM3 + 0x1c) 
#define TIM3_CCER  (volatile unsigned int *)(TIM3 + 0x20) 
#define TIM3_CNT   (volatile unsigned int *)(TIM3 + 0x24) 
#define TIM3_PSC   (volatile unsigned int *)(TIM3 + 0x28) 
#define TIM3_ARR   (volatile unsigned int *)(TIM3 + 0x2c) 
#define TIM3_RCR   (volatile unsigned int *)(TIM3 + 0x30) 
#define TIM3_CCR1  (volatile unsigned int *)(TIM3 + 0x34) 
#define TIM3_CCR2  (volatile unsigned int *)(TIM3 + 0x38) 
#define TIM3_CCR3  (volatile unsigned int *)(TIM3 + 0x3c) 
#define TIM3_CCR4  (volatile unsigned int *)(TIM3 + 0x40) 
#define TIM3_DCR   (volatile unsigned int *)(TIM3 + 0x48) 
#define TIM3_DMAR  (volatile unsigned int *)(TIM3 + 0x4c) 
#define TIM3_AF1   (volatile unsigned int *)(TIM3 + 0x60) 
#define TIM3_AF2   (volatile unsigned int *)(TIM3 + 0x64) 
#define TIM3_TISEL (volatile unsigned int *)(TIM3 + 0x68) 

#define TIM4_CR1   (volatile unsigned int *)(TIM4 + 0x00) 
#define TIM4_CR2   (volatile unsigned int *)(TIM4 + 0x04) 
#define TIM4_SMCR  (volatile unsigned int *)(TIM4 + 0x08) 
#define TIM4_DIER  (volatile unsigned int *)(TIM4 + 0x0c) 
#define TIM4_SR    (volatile unsigned int *)(TIM4 + 0x10) 
#define TIM4_EGR   (volatile unsigned int *)(TIM4 + 0x14) 
#define TIM4_CCMR1 (volatile unsigned int *)(TIM4 + 0x18) 
#define TIM4_CCMR2 (volatile unsigned int *)(TIM4 + 0x1c) 
#define TIM4_CCER  (volatile unsigned int *)(TIM4 + 0x20) 
#define TIM4_CNT   (volatile unsigned int *)(TIM4 + 0x24) 
#define TIM4_PSC   (volatile unsigned int *)(TIM4 + 0x28) 
#define TIM4_ARR   (volatile unsigned int *)(TIM4 + 0x2c) 
#define TIM4_RCR   (volatile unsigned int *)(TIM4 + 0x30) 
#define TIM4_CCR1  (volatile unsigned int *)(TIM4 + 0x34) 
#define TIM4_CCR2  (volatile unsigned int *)(TIM4 + 0x38) 
#define TIM4_CCR3  (volatile unsigned int *)(TIM4 + 0x3c) 
#define TIM4_CCR4  (volatile unsigned int *)(TIM4 + 0x40) 
#define TIM4_DCR   (volatile unsigned int *)(TIM4 + 0x48) 
#define TIM4_DMAR  (volatile unsigned int *)(TIM4 + 0x4c) 
#define TIM4_AF1   (volatile unsigned int *)(TIM4 + 0x60) 
#define TIM4_AF2   (volatile unsigned int *)(TIM4 + 0x64) 
#define TIM4_TISEL (volatile unsigned int *)(TIM4 + 0x68) 

#define TIM5_CR1   (volatile unsigned int *)(TIM5 + 0x00) 
#define TIM5_CR2   (volatile unsigned int *)(TIM5 + 0x04) 
#define TIM5_SMCR  (volatile unsigned int *)(TIM5 + 0x08) 
#define TIM5_DIER  (volatile unsigned int *)(TIM5 + 0x0c) 
#define TIM5_SR    (volatile unsigned int *)(TIM5 + 0x10) 
#define TIM5_EGR   (volatile unsigned int *)(TIM5 + 0x14) 
#define TIM5_CCMR1 (volatile unsigned int *)(TIM5 + 0x18) 
#define TIM5_CCMR2 (volatile unsigned int *)(TIM5 + 0x1c) 
#define TIM5_CCER  (volatile unsigned int *)(TIM5 + 0x20) 
#define TIM5_CNT   (volatile unsigned int *)(TIM5 + 0x24) 
#define TIM5_PSC   (volatile unsigned int *)(TIM5 + 0x28) 
#define TIM5_ARR   (volatile unsigned int *)(TIM5 + 0x2c) 
#define TIM5_RCR   (volatile unsigned int *)(TIM5 + 0x30) 
#define TIM5_CCR1  (volatile unsigned int *)(TIM5 + 0x34) 
#define TIM5_CCR2  (volatile unsigned int *)(TIM5 + 0x38) 
#define TIM5_CCR3  (volatile unsigned int *)(TIM5 + 0x3c) 
#define TIM5_CCR4  (volatile unsigned int *)(TIM5 + 0x40) 
#define TIM5_DCR   (volatile unsigned int *)(TIM5 + 0x48) 
#define TIM5_DMAR  (volatile unsigned int *)(TIM5 + 0x4c) 
#define TIM5_AF1   (volatile unsigned int *)(TIM5 + 0x60) 
#define TIM5_AF2   (volatile unsigned int *)(TIM5 + 0x64) 
#define TIM5_TISEL (volatile unsigned int *)(TIM5 + 0x68) 

#endif

