#ifndef USART_UART_H
#define USART_UART_H

#include "memory.h"

#define USART1_CR1 (volatile unsigned int *)(USART1 + 0x00)
#define USART1_CR2 (volatile unsigned int *)(USART1 + 0x04)
#define USART1_CR3 (volatile unsigned int *)(USART1 + 0x08)
#define USART1_BRR (volatile unsigned int *)(USART1 + 0x0C)
#define USART1_GTPR (volatile unsigned int *)(USART1 + 0x10)
#define USART1_RTOR (volatile unsigned int *)(USART1 + 0x14)
#define USART1_RQR (volatile unsigned int *)(USART1 + 0x18)
#define USART1_ISR (volatile unsigned int *)(USART1 + 0x1C)
#define USART1_ICR (volatile unsigned int *)(USART1 + 0x20)
#define USART1_RDR (volatile unsigned int *)(USART1 + 0x24)
#define USART1_TDR (volatile unsigned int *)(USART1 + 0x28)
#define USART1_PRESC (volatile unsigned int *)(USART1 + 0x2C)

#define USART2_CR1 (volatile unsigned int *)(USART2 + 0x00)
#define USART2_CR2 (volatile unsigned int *)(USART2 + 0x04)
#define USART2_CR3 (volatile unsigned int *)(USART2 + 0x08)
#define USART2_BRR (volatile unsigned int *)(USART2 + 0x0C)
#define USART2_GTPR (volatile unsigned int *)(USART2 + 0x10)
#define USART2_RTOR (volatile unsigned int *)(USART2 + 0x14)
#define USART2_RQR (volatile unsigned int *)(USART2 + 0x18)
#define USART2_ISR (volatile unsigned int *)(USART2 + 0x1C)
#define USART2_ICR (volatile unsigned int *)(USART2 + 0x20)
#define USART2_RDR (volatile unsigned int *)(USART2 + 0x24)
#define USART2_TDR (volatile unsigned int *)(USART2 + 0x28)
#define USART2_PRESC (volatile unsigned int *)(USART2 + 0x2C)

#define USART3_CR1 (volatile unsigned int *)(USART3 + 0x00)
#define USART3_CR2 (volatile unsigned int *)(USART3 + 0x04)
#define USART3_CR3 (volatile unsigned int *)(USART3 + 0x08)
#define USART3_BRR (volatile unsigned int *)(USART3 + 0x0C)
#define USART3_GTPR (volatile unsigned int *)(USART3 + 0x10)
#define USART3_RTOR (volatile unsigned int *)(USART3 + 0x14)
#define USART3_RQR (volatile unsigned int *)(USART3 + 0x18)
#define USART3_ISR (volatile unsigned int *)(USART3 + 0x1C)
#define USART3_ICR (volatile unsigned int *)(USART3 + 0x20)
#define USART3_RDR (volatile unsigned int *)(USART3 + 0x24)
#define USART3_TDR (volatile unsigned int *)(USART3 + 0x28)
#define USART3_PRESC (volatile unsigned int *)(USART3 + 0x2C)

#define USART6_CR1 (volatile unsigned int *)(USART6 + 0x00)
#define USART6_CR2 (volatile unsigned int *)(USART6 + 0x04)
#define USART6_CR3 (volatile unsigned int *)(USART6 + 0x08)
#define USART6_BRR (volatile unsigned int *)(USART6 + 0x0C)
#define USART6_GTPR (volatile unsigned int *)(USART6 + 0x10)
#define USART6_RTOR (volatile unsigned int *)(USART6 + 0x14)
#define USART6_RQR (volatile unsigned int *)(USART6 + 0x18)
#define USART6_ISR (volatile unsigned int *)(USART6 + 0x1C)
#define USART6_ICR (volatile unsigned int *)(USART6 + 0x20)
#define USART6_RDR (volatile unsigned int *)(USART6 + 0x24)
#define USART6_TDR (volatile unsigned int *)(USART6 + 0x28)
#define USART6_PRESC (volatile unsigned int *)(USART6 + 0x2C)

#define UART4_CR1 (volatile unsigned int *)(UART4 + 0x00)
#define UART4_CR2 (volatile unsigned int *)(UART4 + 0x04)
#define UART4_CR3 (volatile unsigned int *)(UART4 + 0x08)
#define UART4_BRR (volatile unsigned int *)(UART4 + 0x0C)
#define UART4_GTPR (volatile unsigned int *)(UART4 + 0x10)
#define UART4_RTOR (volatile unsigned int *)(UART4 + 0x14)
#define UART4_RQR (volatile unsigned int *)(UART4 + 0x18)
#define UART4_ISR (volatile unsigned int *)(UART4 + 0x1C)
#define UART4_ICR (volatile unsigned int *)(UART4 + 0x20)
#define UART4_RDR (volatile unsigned int *)(UART4 + 0x24)
#define UART4_TDR (volatile unsigned int *)(UART4 + 0x28)
#define UART4_PRESC (volatile unsigned int *)(UART4 + 0x2C)

#define UART5_CR1 (volatile unsigned int *)(UART5 + 0x00)
#define UART5_CR2 (volatile unsigned int *)(UART5 + 0x04)
#define UART5_CR3 (volatile unsigned int *)(UART5 + 0x08)
#define UART5_BRR (volatile unsigned int *)(UART5 + 0x0C)
#define UART5_GTPR (volatile unsigned int *)(UART5 + 0x10)
#define UART5_RTOR (volatile unsigned int *)(UART5 + 0x14)
#define UART5_RQR (volatile unsigned int *)(UART5 + 0x18)
#define UART5_ISR (volatile unsigned int *)(UART5 + 0x1C)
#define UART5_ICR (volatile unsigned int *)(UART5 + 0x20)
#define UART5_RDR (volatile unsigned int *)(UART5 + 0x24)
#define UART5_TDR (volatile unsigned int *)(UART5 + 0x28)
#define UART5_PRESC (volatile unsigned int *)(UART5 + 0x2C)

#define UART7_CR1 (volatile unsigned int *)(UART7 + 0x00)
#define UART7_CR2 (volatile unsigned int *)(UART7 + 0x04)
#define UART7_CR3 (volatile unsigned int *)(UART7 + 0x08)
#define UART7_BRR (volatile unsigned int *)(UART7 + 0x0C)
#define UART7_GTPR (volatile unsigned int *)(UART7 + 0x10)
#define UART7_RTOR (volatile unsigned int *)(UART7 + 0x14)
#define UART7_RQR (volatile unsigned int *)(UART7 + 0x18)
#define UART7_ISR (volatile unsigned int *)(UART7 + 0x1C)
#define UART7_ICR (volatile unsigned int *)(UART7 + 0x20)
#define UART7_RDR (volatile unsigned int *)(UART7 + 0x24)
#define UART7_TDR (volatile unsigned int *)(UART7 + 0x28)
#define UART7_PRESC (volatile unsigned int *)(UART7 + 0x2C)

#define UART8_CR1 (volatile unsigned int *)(UART8 + 0x00)
#define UART8_CR2 (volatile unsigned int *)(UART8 + 0x04)
#define UART8_CR3 (volatile unsigned int *)(UART8 + 0x08)
#define UART8_BRR (volatile unsigned int *)(UART8 + 0x0C)
#define UART8_GTPR (volatile unsigned int *)(UART8 + 0x10)
#define UART8_RTOR (volatile unsigned int *)(UART8 + 0x14)
#define UART8_RQR (volatile unsigned int *)(UART8 + 0x18)
#define UART8_ISR (volatile unsigned int *)(UART8 + 0x1C)
#define UART8_ICR (volatile unsigned int *)(UART8 + 0x20)
#define UART8_RDR (volatile unsigned int *)(UART8 + 0x24)
#define UART8_TDR (volatile unsigned int *)(UART8 + 0x28)
#define UART8_PRESC (volatile unsigned int *)(UART8 + 0x2C)

#define LPUART1_CR1 (volatile unsigned int *)(LPUART1 + 0x00)
#define LPUART1_CR2 (volatile unsigned int *)(LPUART1 + 0x04)
#define LPUART1_CR3 (volatile unsigned int *)(LPUART1 + 0x08)
#define LPUART1_BRR (volatile unsigned int *)(LPUART1 + 0x0C)
#define LPUART1_RQR (volatile unsigned int *)(LPUART1 + 0x18)
#define LPUART1_ISR (volatile unsigned int *)(LPUART1 + 0x1C)
#define LPUART1_ICR (volatile unsigned int *)(LPUART1 + 0x20)
#define LPUART1_RDR (volatile unsigned int *)(LPUART1 + 0x24)
#define LPUART1_TDR (volatile unsigned int *)(LPUART1 + 0x28)
#define LPUART1_PRESC (volatile unsigned int *)(LPUART1 + 0x2c)

#endif
